ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; -- 계정명 C## 안쓰고 만들 수 있게 하는 거, 만드시고 FALSE 하면 됩니다

CREATE USER market IDENTIFIED BY tiger;

GRANT CONNECT TO market;

GRANT RESOURCE TO market;

GRANT CREATE TABLE TO market;

GRANT CREATE VIEW TO market;

GRANT CREATE SEQUENCE TO market;

ALTER USER market DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

commit;