/* 시퀀스 삭제 */
/* 사용자번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_USER_NUM;
/* 배송지번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_ADDR_NUM;
/* 사업자등록번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_COM_NUM;
/* 관리자번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_ADM_NUM;
/* 카테고리번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_CAT_NUM;
/* 상품번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_PRD_NUM;
/* 이미지번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_IMG_NUM;
/* 찜번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_FAV_NUM;
/* 후기번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_REV_NUM;
/* 신고번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_REP_NUM;
/* 사기조회번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_SCAM_NUM;
/* 채팅방번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_CHATROOM_NUM;
/* 메세지번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_MSG_ID;
/* 공지사항번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_NOT_NUM;
/* FAQ번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_FAQ_NUM;
/* 문의사항번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_INQ_NUM;
/* 이벤트번호 시퀀스 삭제 */
DROP SEQUENCE SEQ_EVT_NUM;

/* 테이블 삭제 */
/* 사용자 테이블 삭제 */
DROP TABLE USERS
CASCADE CONSTRAINTS;
/* 계좌 테이블 삭제 */
DROP TABLE BANK
CASCADE CONSTRAINTS;
/* 배송지 테이블 삭제 */
DROP TABLE ADDRESS
CASCADE CONSTRAINTS;
/* 기업 테이블 삭제 */
DROP TABLE COMPANY
CASCADE CONSTRAINTS;
/* 관리자 테이블 삭제 */
DROP TABLE ADMIN
CASCADE CONSTRAINTS;
/* 카테고리 테이블 삭제 */
DROP TABLE CATEGORY
CASCADE CONSTRAINTS;
/* 상품 테이블 삭제 */
DROP TABLE PRODUCT
CASCADE CONSTRAINTS;
/* 이미지 테이블 삭제 */
DROP TABLE IMAGE
CASCADE CONSTRAINTS;
/* 찜 테이블 삭제 */
DROP TABLE FAVORITE
CASCADE CONSTRAINTS;
/* 거래 테이블 삭제 */
DROP TABLE TRADES
CASCADE CONSTRAINTS;
/* 결제 테이블 삭제 */
DROP TABLE PAYMENTS
CASCADE CONSTRAINTS;
/* 후기 테이블 삭제 */
DROP TABLE REVIEW
CASCADE CONSTRAINTS;
/* 신고 테이블 삭제 */
DROP TABLE REPORT
CASCADE CONSTRAINTS;
/* 사기조회 테이블 삭제 */
DROP TABLE SCAM
CASCADE CONSTRAINTS;
/* 채팅방 테이블 삭제 */
DROP TABLE CHATROOM
CASCADE CONSTRAINTS;
/* 채팅메세지 테이블 삭제 */
DROP TABLE CHATMESSAGE
CASCADE CONSTRAINTS;
/* 공지사항 테이블 삭제 */
DROP TABLE NOTICE
CASCADE CONSTRAINTS;
/* FAQ 테이블 삭제 */
DROP TABLE FAQ
CASCADE CONSTRAINTS;
/* 문의사항 테이블 삭제 */
DROP TABLE INQUIRY
CASCADE CONSTRAINTS;
/* 문의답변 테이블 삭제 */
DROP TABLE ANSWER
CASCADE CONSTRAINTS;
/* 이벤트 테이블 삭제 */
DROP TABLE EVENT
CASCADE CONSTRAINTS;

/* 테이블 생성 */
/* 사용자 테이블 생성 */
CREATE TABLE USERS (
	USER_NUM		VARCHAR2(255)		NOT NULL, /* 사용자번호 */
	NAME				VARCHAR2(255)		NOT NULL, /* 사용자이름 */
	NICKNAME		VARCHAR2(255)		NULL, /* 사용자닉네임 */
	IMAGE				VARCHAR2(4000)	NULL, /* 사용자프로필사진 */
	EMAIL				VARCHAR2(255)		NOT NULL, /* 사용자이메일 */
	PASS				VARCHAR2(255)		NOT NULL, /* 사용자닉네임 */
	TEL					VARCHAR2(255)		NOT NULL, /* 사용자전화번호 */
	ZIPCODE			VARCHAR2(4000)	NOT NULL, /* 사용자우편번호 */
	ADDRESS			VARCHAR2(4000)	NOT NULL, /* 사용자주소 */
	MANNER			NUMBER(10)			DEFAULT 100, /* 사용자신뢰지수 */
	POINT				NUMBER(30)			DEFAULT 0, /* 사용자포인트 */
	INPUT_DATE	DATE						DEFAULT SYSDATE, /* 사용자가입일 */
	BAN_DATE		DATE						NULL, /* 사용자정지일 */
	BANTYPE			VARCHAR2(255)		DEFAULT 'N', /* 사용자정지여부(Y,N) */
	DRAW_DATE		DATE						NULL, /* 사용자탈퇴일 */
	WITHDRAW		VARCHAR2(255)		DEFAULT 'N', /* 사용자탈퇴여부(Y,N) */
	AUTH_CODE		VARCHAR2(255)		NULL /* 사용자인증번호 */
);

/* 계좌 테이블 생성 */
CREATE TABLE BANK (
	USER_NUM	VARCHAR2(255)		NOT NULL, /* 사용자번호 */
	NAME			VARCHAR2(255)		NOT NULL, /* 계좌예금주 */
	BANK_NAME	VARCHAR2(255)		NOT NULL, /* 계좌은행명 */
	BANK_NUM	VARCHAR2(4000)	NOT NULL, /* 계좌번호 */
	BANK_TYPE	VARCHAR2(255)		DEFAULT 'Y'  /* 대표계좌여부(Y,N) */
);

/* 배송지 테이블 생성 */
CREATE TABLE ADDRESS (
	ADDR_NUM				NUMBER(10)			NOT NULL, /* 배송지번호 */
	NAME						VARCHAR2(255)		NOT NULL, /* 주문자 */
	RECIPIENT_NAME	VARCHAR2(255)		NOT NULL, /* 받는사람 */
	TEL							VARCHAR2(255)		NOT NULL, /* 전화번호 */
	ZIPCODE					VARCHAR2(255)		NOT NULL, /* 우편번호 */
	ADDRESS					VARCHAR2(3000)	NOT NULL, /* 주소 */
	ADDR_TYPE				VARCHAR2(255)		DEFAULT 'N', /* 대표배송지여부(Y,N) */
	USER_NUM				VARCHAR2(255)		NOT NULL /* 사용자번호 */
);

/* 기업 테이블 생성 */
CREATE TABLE COMPANY (
	COM_NUM			VARCHAR2(255)		NOT NULL, /* 사업자등록번호 */
	COM_NAME		VARCHAR2(255)		NOT NULL, /* 기업이름 */
	CEO_NAME		VARCHAR2(255)		NOT NULL, /* 기업대표자명 */
	NAME				VARCHAR2(255)		NOT NULL, /* 기업담당자명 */
	IMAGE				VARCHAR2(4000)	NULL, /* 기업프로필사진 */
	ID					VARCHAR2(255)		NOT NULL, /* 기업ID */
	PASS				VARCHAR2(255)		NOT NULL, /* 기업비밀번호 */
	TEL					VARCHAR2(255)		NOT NULL, /* 기업전화번호 */
	BUSINESSNUM VARCHAR2(255)		NULL, /* 사업자등록번호 */
	ZIPCODE			VARCHAR2(255)		NOT NULL, /* 기업우편번호 */
	ADDRESS			VARCHAR2(4000)	NOT NULL, /* 기업주소 */
	INPUT_DATE	DATE						DEFAULT SYSDATE, /* 기업가입일 */
	DRAW_DATE		DATE						NULL, /* 기업탈퇴일 */
	WITHDRAW		VARCHAR2(255)		DEFAULT 'N' /* 기업탈퇴여부(Y,N) */
);

/* 관리자 테이블 생성 */
CREATE TABLE ADMIN (
	ADM_NUM			VARCHAR2(255)	NOT NULL, /* 관리자사번 */
	NAME				VARCHAR2(255)	NOT NULL, /* 관리자이름 */
	ID					VARCHAR2(255)	NOT NULL, /* 관리자ID */
	PASS				VARCHAR2(255)	NOT NULL, /* 관리자비밀번호 */
	TEL					VARCHAR2(255)	NULL, /* 관리자전화번호 */
	INPUT_DATE	DATE					DEFAULT SYSDATE, /* 관리자가입일 */
	BAN_DATE		DATE					NULL, /* 관리자정지일 */
	BANTYPE			VARCHAR2(255)	DEFAULT 'N', /* 관리자정지여부(Y,N) */
	ROLLTYPE		NUMBER(5)			DEFAULT 2 /* 관리자계정타입(1,2) */
);

/* 카테고리 테이블 생성 */
CREATE TABLE CATEGORY (
	CAT_NUM	NUMBER(10)	NOT NULL, /* 카테고리번호 */
	NAME	VARCHAR2(255)	NULL /* 카테고리이름 */
);


/* 상품 테이블 생성 */
CREATE TABLE PRODUCT (
	PRD_NUM				VARCHAR2(255)		NOT NULL, /* 상품번호 */
	TITLE					VARCHAR2(500)		NOT NULL, /* 상품제목 */
	CONTENT				VARCHAR2(4000)	NOT NULL, /* 상품내용 */
	PRICE					NUMBER(10)			DEFAULT 0, /* 상품가격 */
	LOCATION1			VARCHAR2(4000)	NULL, /* 상품등록지역 */
	INPUT_DATE		DATE						DEFAULT SYSDATE, /* 상품작성일 */
	APPOINT_TYPE	VARCHAR2(255)		DEFAULT 'N', /* 상품예약여부(Y,N) */
	HIDDEN_TYPE		VARCHAR2(255)		DEFAULT 'N', /* 상품숨김여부(Y,N) */
	SELL_TYPE			VARCHAR2(255)		DEFAULT 'N', /* 상품판매여부(Y,N) */
	PRD_CNT				NUMBER(10)			DEFAULT 1, /* 상품재고 */
	CLICK_NUM			NUMBER(10)			DEFAULT 0, /* 상품조회수 */
	SAFE_TYPE			VARCHAR2(255)		DEFAULT 'N', /* 안전거래여부(Y,N) */
	MEET_TYPE			VARCHAR2(255)		DEFAULT 'N', /* 직거래여부(Y,N) */
	DELIVERY_TYPE	VARCHAR2(255)		DEFAULT 'N', /* 택배거래여부(Y,N) */
	USER_NUM			VARCHAR2(255)		NULL, /* 사용자번호 */
	CAT_NUM				NUMBER(10)			NOT NULL, /* 카테고리번호 */
	COM_NUM				VARCHAR2(255)		NULL, /* 사업자등록번호 */
	IMG_NUM				NUMBER(10)			NULL, /* 이미지번호 */
	LIKE_NUM			NUMBER(10)			DEFAULT 0, /* 상품찜수 */
	ADMIN_SCORE		NUMBER(10)			DEFAULT 0 /* 관리자 점수 */
);

/* 이미지 테이블 생성 */
CREATE TABLE IMAGE (
	IMG_NUM			NUMBER(10)			NOT NULL, /* 이미지번호 */
	MAIN_IMAGE	VARCHAR2(4000)	NULL, /* 메인이미지 */
	SUB_IMAGE1	VARCHAR2(4000)	NULL, /* 추가이미지1 */
	SUB_IMAGE2	VARCHAR2(4000)	NULL, /* 추가이미지2 */
	SUB_IMAGE3	VARCHAR2(4000)	NULL, /* 추가이미지3 */
	SUB_IMAGE4	VARCHAR2(4000)	NULL, /* 추가이미지4 */
	IMAGE_TYPE	VARCHAR2(255)		NOT NULL /* 이미지게시물타입(1,2,3)*/
);

/* 찜 테이블 생성 */
CREATE TABLE FAVORITE (
	FAV_NUM			NUMBER(10)			NOT NULL, /* 찜번호 */
	INPUT_DATE	DATE						DEFAULT SYSDATE, /* 찜저장일 */
	PRD_NUM			VARCHAR2(255)		NOT NULL, /* 상품번호 */
	USER_NUM		VARCHAR2(255)		NOT NULL /* 사용자번호 */
);

/* 거래 테이블 생성 */
CREATE TABLE TRADES (
	TRADE_ID			NUMBER(10)			NOT NULL, /* 거래자ID*/
	BUYER_ID			VARCHAR2(255)		NOT NULL, /* 구매자ID */
	SELLER_ID			VARCHAR2(255)		NOT NULL, /* 판매자ID */
	TRADE_STATUS	VARCHAR2(200)		DEFAULT '판매중', /* 거래상태 */
	TRADE_DATE		DATE						DEFAULT SYSDATE, /* 거래일*/
	DELIVERY_NUM	NUMBER(10)			NULL,
	PRD_NUM				VARCHAR2(255)		NOT NULL /* 상품번호 */
);

/* 결제 테이블 생성 */
CREATE TABLE PAYMENTS (
	PAYMENT_UID		VARCHAR2(255)	NOT NULL, /* 결제자*/
	AMOUNT				NUMBER(10)		NOT NULL, /* 결제금액 */
	METHOD				VARCHAR2(200)	NOT NULL, /* 결제수단 */
	CARD_COMPANY	VARCHAR2(200)	NULL, 		/* 결제회사 */
	PATMENT_DATE	DATE					DEFAULT SYSDATE, /* 결제일 */
	TRADE_ID			VARCHAR2(255)	NOT NULL /* 거래자 */
);

/* 후기 테이블 생성 */
CREATE TABLE REVIEW (
	REV_NUM			NUMBER(10)			NOT NULL, /* 후기번호 */
	CONTENT			VARCHAR2(4000)	NOT NULL, /* 후기내용 */
	NAME				VARCHAR2(255)		NOT NULL, /* 후기작성자 */
	INPUT_DATE	DATE						DEFAULT SYSDATE, /* 후기작성일 */
	REPORT_CNT	NUMBER(10)			DEFAULT 0, /* 누적신고수 */
	HIDDEN_TYPE	VARCHAR2(255)		DEFAULT 'N', /* 후기숨김여부(Y,N) */
	KEYWORD			VARCHAR2(255)		NULL, /* 후기선택키워드(최고예요,좋아요,별로에요) */
	PRD_NUM			VARCHAR2(255)		NOT NULL /* 상품번호 */
);

/* 신고 테이블 생성 */
CREATE TABLE REPORT (
	REP_NUM			NUMBER(10)			NOT NULL, /* 신고번호 */
	TITLE				VARCHAR2(500)		NOT NULL, /* 신고제목 */
	CONTENT			VARCHAR2(4000)	NOT NULL, /* 신고내용 */
	NAME				VARCHAR2(255)		NOT NULL, /* 신고자 */
	INPUT_DATE	DATE						DEFAULT SYSDATE, /* 신고일 */
	REPORT_TYPE	NUMBER(10)			NULL, /* 신고타입(상품,사용자) */
	SEARCH_TYPE	VARCHAR2(255)		NULL, /* 사기조회가능여부(Y,N) */
	USER_NUM		VARCHAR2(255)		NULL, /* 사용자번호 */
	PRD_NUM			VARCHAR2(255)		NULL  /* 상품 번호 */
);

/* 사기조회 테이블 생성 */
CREATE TABLE SCAM (
  SCAM_NUM   	NUMBER(10)       NOT NULL, /* 사기조회번호 */
  INPUT_VALUE VARCHAR2(4000)   NOT NULL, /* 사용자입력값 */
  INPUT_DATE  DATE             DEFAULT SYSDATE /* 사기조회일 */
);

/* 채팅방 테이블 생성 */
CREATE TABLE CHATROOM (
	CHATROOM_NUM	NUMBER(10)		NOT NULL, /* 채팅방번호*/
	SELLER_NUM		VARCHAR2(255)	NOT NULL, /* 판매자회원번호 */
	BUYER_NUM			VARCHAR2(255)	NOT NULL, /* 구매자회원번호 */
	CREATE_DATE		DATE					DEFAULT SYSDATE, /* 채팅방생성일시 */
	UPDATE_DATE		DATE					NULL, /* 채팅방수정일 */
	READ_STATUS		VARCHAR2(255)	DEFAULT 'N', /* 채팅방상태(Y,N)*/
	PRD_NUM				VARCHAR2(255)	NULL, /* 상품번호 */
	USER_NUM			VARCHAR2(255)	NULL /* 사용자번호 */
);

/* 채팅메세지 테이블 생성 */
CREATE TABLE CHATMESSAGE (
	MSG_ID				NUMBER(10)			NULL,
	CONTENT				VARCHAR2(1500)	NOT NULL,
	CREATE_DATE		DATE	DEFAULT 	SYSDATE,
	IS_READ				VARCHAR2(255)		DEFAULT 'N',
	IMG_PATH			VARCHAR2(300)		NULL,
	CHATROOM_NUM	NUMBER(10)			NULL,
	USER_NUM			VARCHAR2(255)   NOT NULL
);

/* 공지사항 테이블 생성 */
CREATE TABLE NOTICE(
	NOT_NUM			NUMBER(10)			NOT NULL, /* 공지사항번호 */
	TITLE				VARCHAR2(500)		NOT NULL, /* 공지사항제목 */
	CONTENT			CLOB						NOT NULL, /* 공지사항내용 */
	NAME				VARCHAR2(255)		NOT NULL, /* 공지사항작성자 */
	INPUT_DATE	DATE						DEFAULT SYSDATE, /* 공지사항작성자 */
	STATUS_TYPE	VARCHAR2(255)		DEFAULT '공지', /* 공지사항상태(공지,미공지) */
	ADM_NUM			VARCHAR2(255)		NOT NULL /* 관리자사번 */
);

/* FAQ 테이블 생성 */
CREATE TABLE FAQ (
	FAQ_NUM			NUMBER(10)			NOT NULL, /* FAQ번호 */
	TITLE				VARCHAR2(500)		NOT NULL, /* FAQ제목 */
	CONTENT			CLOB						NOT NULL, /* FAQ내용 */
	NAME				VARCHAR2(255)		NOT NULL, /* FAQ작성자 */
	INPUT_DATE	DATE						DEFAULT SYSDATE, /* FAQ작성일 */
	FAQ_TYPE		VARCHAR2(255)		NULL, /* FAQ타입(거래문의,이용문의,회원/계정,운영정책,기타) */
	ADM_NUM			VARCHAR2(255)		NOT NULL  /* 관리자사번 */
);

/* 문의사항 테이블 생성 */
CREATE TABLE INQUIRY (
	INQ_NUM			NUMBER(10)			NOT NULL, /* 문의사항번호 */
	TITLE				VARCHAR2(500)		NOT NULL, /* 문의사항제목 */
	CONTENT			VARCHAR2(4000)	NOT NULL, /* 문의사항내용 */
	NAME				VARCHAR2(255)		NOT NULL, /* 문의사항작성자 */
	INPUT_DATE	DATE	DEFAULT 	SYSDATE, /* 문의사항작성일 */
	STATUS_TYPE	VARCHAR2(255)		DEFAULT '대기', /* 문의사항상태(대기,답변완료) */
	INQUIRY_TYPE VARCHAR2(500)	NULL, /* 문의사항유형(주문/결제, 배송, 환불, 기타) */
	USER_NUM		NUMBER(10)			NOT NULL, /* 사용자번호 */
	ADM_NUM			VARCHAR2(255)		NULL, /* 관리자사번 */
	IMG_NUM			NUMBER(10)			NULL /* 이미지번호 */
);

/* 문의답변 테이블 생성 */
CREATE TABLE ANSWER (
	INQ_NUM			NUMBER(10)			NOT NULL, /* 문의사항번호 */
	CONTENT			VARCHAR2(4000)	NOT NULL, /* 문의답변내용 */
	INPUT_TYPE	DATE						DEFAULT SYSDATE, /* 문의답변작성일*/
	ADM_NUM			VARCHAR2(255)		NOT NULL /* 문의답변작성자 */
);

/* 이벤트 테이블 생성 */
CREATE TABLE EVENT (
	EVT_NUM			NUMBER(10)			NOT NULL, /* 이벤트번호 */
	TITLE				VARCHAR2(500)		NULL, /* 이벤트제목 */
	CONTENT			CLOB						NOT NULL, /* 이벤트내용 */
	NAME				VARCHAR2(255)		NOT NULL, /* 이벤트작성자 */
	START_DATE	DATE						NULL, /* 이벤트시작일 */
	END_DATE		DATE						NULL, /* 이벤트종료일 */
	EVT_TYPE		NUMBER(10)			DEFAULT 1, /* 이벤트게시Type(1,2,3)*/
	ADM_NUM			VARCHAR2(255)		NOT NULL, /* 관리자사번 */
	IMG_NUM			NUMBER(10)			NULL, /* 이미지번호 */
	MAIN_TYPE		VARCHAR2(255)		DEFAULT 'N' /* 메인페이지표시여부(Y,N) */
);

/* 시퀀스 생성 */
/* 사용자번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_USER_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 사업자등록번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_COM_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 관리자번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_ADM_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 카테고리번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_CAT_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 상품번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_PRD_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 메시지번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_MSG_ID
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 공지사항번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_NOT_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* FAQ번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_FAQ_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 후기번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_REV_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 사기조회번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_SCAM_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 채팅방번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_CHATROOM_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 찜번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_FAV_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 문의사항번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_INQ_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 이미지번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_IMG_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 이벤트번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_EVT_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 배송지번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_ADDR_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* 신고번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_REP_NUM
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 9999999999;

/* Primary key 설정 */
/* 사용자번호 PK 설정 */
ALTER TABLE USERS
  ADD CONSTRAINT PK_USERS PRIMARY KEY (USER_NUM);
/* 계좌테이블.사용자번호 PK 설정 */
ALTER TABLE BANK
  ADD CONSTRAINT PK_BANK PRIMARY KEY (USER_NUM);
/* 배송지번호 PK 설정 */
ALTER TABLE ADDRESS
  ADD CONSTRAINT PK_ADDRESS PRIMARY KEY (ADDR_NUM);
/* 사업자등록번호 PK 설정 */
ALTER TABLE COMPANY
  ADD CONSTRAINT PK_COMPANY PRIMARY KEY (COM_NUM);
/* 관리자번호 PK 설정 */
ALTER TABLE ADMIN
  ADD CONSTRAINT PK_ADMIN PRIMARY KEY (ADM_NUM);
/* 카테고리번호 PK 설정 */
ALTER TABLE CATEGORY
  ADD CONSTRAINT PK_CATEGORY PRIMARY KEY (CAT_NUM);
/* 상품번호 PK 설정 */
ALTER TABLE PRODUCT
  ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (PRD_NUM);
/* 이미지번호 PK 설정 */
ALTER TABLE IMAGE
  ADD CONSTRAINT PK_IMAGE PRIMARY KEY (IMG_NUM);
/* 찜번호 PK 설정 */
ALTER TABLE FAVORITE
  ADD CONSTRAINT PK_FAVORITE PRIMARY KEY (FAV_NUM);
/* 거래자ID PK 설정 */
ALTER TABLE TRADES
  ADD CONSTRAINT PK_TRADES PRIMARY KEY (TRADE_ID);
/* 후기번호 PK 설정 */
ALTER TABLE REVIEW
  ADD CONSTRAINT PK_REVIEW PRIMARY KEY (REV_NUM);
/* 신고번호 PK 설정 */
ALTER TABLE REPORT
  ADD CONSTRAINT PK_REPORT PRIMARY KEY (REP_NUM);
/* 사기조회번호 PK 설정 */
ALTER TABLE SCAM
  ADD CONSTRAINT PK_SCAM PRIMARY KEY (SCAM_NUM);
/* 채팅방번호 PK 설정 */
ALTER TABLE CHATROOM
  ADD CONSTRAINT PK_CHATROOM PRIMARY KEY (CHATROOM_NUM);
/* 메세지번호 PK 설정 */
ALTER TABLE CHATMESSAGE
  ADD CONSTRAINT PK_CHATMESSAGE PRIMARY KEY (MSG_ID);
/* 공지사항번호 PK 설정 */
ALTER TABLE NOTICE
  ADD CONSTRAINT PK_NOTICE PRIMARY KEY (NOT_NUM);
/* FAQ번호 PK 설정 */
ALTER TABLE FAQ
  ADD CONSTRAINT PK_FAQ PRIMARY KEY (FAQ_NUM);
/* 문의사항번호 PK 설정 */
ALTER TABLE INQUIRY
  ADD CONSTRAINT PK_INQUIRY PRIMARY KEY (INQ_NUM);
/* 문의답변테이블.문의사항번호 PK 설정 */
ALTER TABLE ANSWER
  ADD CONSTRAINT PK_ANSWER PRIMARY KEY (INQ_NUM);
/* 이벤트번호 PK 설정 */
ALTER TABLE EVENT
  ADD CONSTRAINT PK_EVENT PRIMARY KEY (EVT_NUM);


